name: Publish
on:
  workflow_run:
    workflows: [CI]
    branches: 
      - releases,
      - main
    
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
    - uses: actions/checkout@v2
    - name: Use Node.js enironment
      uses: actions/setup-node@v3
      with:
          node-version: 16.x
          cache: 'npm'
    - run: npm ci
    - run: npm run semantic-release
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}